name: order_app
description: A new Flutter application.

publish_to: 'none'

version: 0.1.1+5

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^5.0.0
  firebase_core: ^1.0.2
  firebase_auth: ^1.0.1
  cloud_firestore: ^2.2.0
  font_awesome_flutter: ^9.0.0
  google_sign_in: ^5.0.4
  flutter_facebook_auth: ^3.4.0
  image_picker: ^0.8.0+1
  firebase_storage: ^8.1.1
  permission_handler: ^8.0.1
  flutter_launcher_icons: ^0.9.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Montserat
      fonts:
        - asset: assets/font/Montserrat-Bold.ttf
        - asset: assets/font/Montserrat-Regular.ttf
        - asset: assets/font/Montserrat-Light.ttf

flutter_icons:
  ios: true
  android: true
  image_path: "assets/app_icon/app-icon.png"

